import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '../components/Navbar'
import Sidebar from '../components/Sidebar'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

    <div className="flex flex-col h-screen">
      {/* <Navbar /> */}
      <div className='flex flex-1 overflow-hidden'>
        <Sidebar />
        <main className="flex-1 overflow-y-auto text-white">{children}</main>
      </div>
    </div>
      {/* <body className={inter.className}>{children}</body> */}
    </html>
  )
}
